apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/psql2"

